### ISSUE TITLE
add gitter chat room

### ISSUE THREAD

**Issue by SOSANA** [shama/letswritecode#4]
Can't say enought thank yous!

Curious if you would entertain a gitter chat room for this project?

**Comment by shama** [comment]
That is a really interesting idea. Although between my family, work and OSS, I don't have the capacity to actively answer questions in a gitter room. People might have a better chance of getting help using the support channels for the specific projects they're looking for help on rather than waiting for me to respond.

**Comment by SOSANA** [comment]
couldn't agree more as I am busy with a big family, work, and OSS.

Thanks again and keep up the good work!
